services:
  # 1. The Database
  db:
    image: postgres:15-alpine
    container_name: school_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edutrak_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edutrak_network

  # 2. The Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: school_backend
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    networks:
      - edutrak_network
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/edutrak_db
      JWT_SECRET: your_dev_secret_key
    depends_on:
      - db

  # 3. The Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: school_frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"

    networks:
      - edutrak_network
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - backend

networks:
  edutrak_network:
    driver: bridge

volumes:
  postgres_data: {}
  frontend_node_modules: {}